import localFont from "next/font/local";

const roobert = localFont({
  src: [
    {
      path: "../../public/fonts/roobert/Roobert-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/roobert/Roobert-Medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Skinstric",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roobert.className}>
        {children}
      </body>
    </html>
  );
}
